os: linux
dist: focal
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install coverage
script:
  - coverage run -m pytest -m unit
after_success:
  - coverage xml
  - pip install codacy-coverage
  - python-codacy-coverage -r coverage.xml
